# **SOAL 1**

In [ ]:
#Import Data
import pandas as pd
df = pd.read_excel('/content/Kompi 9 Data.xlsx')
df

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm)
0,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155
3,SC60906,Lisa Nessa Safitri,Matematika,43.0,149
4,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168
5,SC60923,Najwa Mayang Vianisa,Statistika,65.0,165
6,SC60913,Deana Nathania Damayanti,Informatika,50.0,165
7,SC60911,Tiara Dwi Maharani,Ekonomi,55.0,156
8,SC60912,Alvina Az-Zahra Adiputri,Statistika,50.0,159
9,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153
10,SC60908,Nabila Salmaa Azzahra,Management,59.0,170
11,SC60920,Aufa Fahmi Widyatna,Matematika,55.0,167
12,SC60918,Silviana Siagian,Sistem Informasi,45.0,165
13,SC60905,Haris Munandar,Teknik Pertanian,70.0,173
14,SC60903,Dede Meilawati,Sistem Informasi,55.0,159
15,SC60921,Faris Reza Hutama,Statistika,47.0,168
16,SC60909,PANGKY MANGKURAJA,Statistika,52.0,166
17,SC60904,Maulana Raji Shofil Fuadi,Aktuaria,67.0,170
18,SC60919,Ahmad Rosyiq Al Farisi,Geofisika,50.0,160
19,SC60924,Reza Sadiya Purwadwika,Sains Data,55.0,163
20,SC60902,Asmiranti,Teknologi Informasi,49.9,152
21,SC60917,Paskahlin Pretty,MANAJEMEN,60.0,165
22,SC60901,Afifah Mutiah Nurdin,Statistika,47.0,155
23,SC60910,Roisatul Laila Hikmah,Pendidikan IPA,50.0,156
24,SC60916,Muhammad Iqbal,Oseanografi,55.0,167

## 1. Identifikasi dan jelaskan tipe data apa saja yang ada pada dataframe, ada berapa kolom dan baris, serta informasi apa saja yang terkandung dalam data tersebut?

In [ ]:
#Tipe Data
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25 entries, 0 to 24
Data columns (total 5 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Nomor Peserta      25 non-null     object
 1   Nama Lengkap       25 non-null     object
 2   Jurusan            25 non-null     object
 3   Berat Badan (kg)   25 non-null     float64
 4   Tinggi Badan (cm)  25 non-null     int64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.1+ KB

## 2. Hitunglah BMI setiap siswa dengan rumus BMI = Berat badan (kg)/(Tinggi Badan (m))^2

In [ ]:
#Menghitung BMI
BMI = df['Berat Badan (kg)']/((df['Tinggi Badan (cm)']/100)**2)
round(BMI,2)

0     24.02
1     17.01
2     21.64
3     19.37
4     23.74
5     23.88
6     18.37
7     22.60
8     19.78
9     17.94
10    20.42
11    19.72
12    16.53
13    23.39
14    21.76
15    16.65
16    18.87
17    23.18
18    19.53
19    20.70
20    21.60
21    22.04
22    19.56
23    20.55
24    19.72
dtype: float64

## 3. Buatlah program untuk menghitung BMI!

In [ ]:
berat = float(input("Masukkan berat badan dalam kg: "))
tinggi = float(input("Masukkan tinggi badan dalam m: "))
def BMI(bb, tb):
  BMI = bb/(tb**2)
  #if (BMI)
  return round(BMI,2)
BMI(berat, tinggi)

Masukkan berat badan dalam kg: 50
Masukkan tinggi badan dalam m: 1.28

30.52

## 4. Update dataframe df dengan menambahkan hasil perhitungan soal nomor 2, beri nama kolom BMI.

In [ ]:
#Menambahkan Kolom BMI
df['BMI'] = round(df['Berat Badan (kg)']/((df['Tinggi Badan (cm)']/100)**2),2)
df.head()

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI
0,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167,24.02
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64
3,SC60906,Lisa Nessa Safitri,Matematika,43.0,149,19.37
4,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168,23.74

## 5. Buatlah status BMI untuk setiap siswa dari kategori berikut, lalu simpan data statusnya dengan nama kolom Status BMI.
*   Normal: 18.5-24.9
*   Overweight: 25.0-29.9
*   Obesity: 30.0-34.9
*   Underweight: < 18.5

In [ ]:
#Membuat Function Kondisi Status BMI
def status_BMI(BMI):
  if BMI >= 18.5 and BMI <= 24.9:
    return 'Normal'
  elif BMI >= 25.0 and BMI <= 29.9:
    return 'Overweight'
  elif BMI >= 30.0 and BMI <= 34.9:
    return 'Obesity'
  elif BMI < 18.5:
    return 'Underweight'
#Menambahkan Kolom
df['Status BMI'] = df['BMI'].apply(status_BMI)
df.head()

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167,24.02,Normal
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01,Underweight
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64,Normal
3,SC60906,Lisa Nessa Safitri,Matematika,43.0,149,19.37,Normal
4,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168,23.74,Normal

## 6.
* Buatlah variabel baru lalu urutkan data berdasarkan tinggi badan dari yang tertinggi ke rendah.
* Buat variabel baru lalu urutkan data berdasarkan nama dari Z-A.

In [ ]:
#Soal a
df.sort_values(by=['Tinggi Badan (cm)'], ascending=False)

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
13,SC60905,Haris Munandar,Teknik Pertanian,70.0,173,23.39,Normal
10,SC60908,Nabila Salmaa Azzahra,Management,59.0,170,20.42,Normal
17,SC60904,Maulana Raji Shofil Fuadi,Aktuaria,67.0,170,23.18,Normal
15,SC60921,Faris Reza Hutama,Statistika,47.0,168,16.65,Underweight
4,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168,23.74,Normal
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01,Underweight
0,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167,24.02,Normal
11,SC60920,Aufa Fahmi Widyatna,Matematika,55.0,167,19.72,Normal
24,SC60916,Muhammad Iqbal,Oseanografi,55.0,167,19.72,Normal
16,SC60909,PANGKY MANGKURAJA,Statistika,52.0,166,18.87,Normal
6,SC60913,Deana Nathania Damayanti,Informatika,50.0,165,18.37,Underweight
5,SC60923,Najwa Mayang Vianisa,Statistika,65.0,165,23.88,Normal
21,SC60917,Paskahlin Pretty,MANAJEMEN,60.0,165,22.04,Normal
12,SC60918,Silviana Siagian,Sistem Informasi,45.0,165,16.53,Underweight
19,SC60924,Reza Sadiya Purwadwika,Sains Data,55.0,163,20.70,Normal
18,SC60919,Ahmad Rosyiq Al Farisi,Geofisika,50.0,160,19.53,Normal
8,SC60912,Alvina Az-Zahra Adiputri,Statistika,50.0,159,19.78,Normal
14,SC60903,Dede Meilawati,Sistem Informasi,55.0,159,21.76,Normal
7,SC60911,Tiara Dwi Maharani,Ekonomi,55.0,156,22.60,Normal
23,SC60910,Roisatul Laila Hikmah,Pendidikan IPA,50.0,156,20.55,Normal
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64,Normal
22,SC60901,Afifah Mutiah Nurdin,Statistika,47.0,155,19.56,Normal
9,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153,17.94,Underweight
20,SC60902,Asmiranti,Teknologi Informasi,49.9,152,21.60,Normal
3,SC60906,Lisa Nessa Safitri,Matematika,43.0,149,19.37,Normal

In [ ]:
#Soal b
df.sort_values(by=['Nama Lengkap'], ascending=False)

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64,Normal
7,SC60911,Tiara Dwi Maharani,Ekonomi,55.0,156,22.60,Normal
12,SC60918,Silviana Siagian,Sistem Informasi,45.0,165,16.53,Underweight
23,SC60910,Roisatul Laila Hikmah,Pendidikan IPA,50.0,156,20.55,Normal
19,SC60924,Reza Sadiya Purwadwika,Sains Data,55.0,163,20.70,Normal
21,SC60917,Paskahlin Pretty,MANAJEMEN,60.0,165,22.04,Normal
16,SC60909,PANGKY MANGKURAJA,Statistika,52.0,166,18.87,Normal
5,SC60923,Najwa Mayang Vianisa,Statistika,65.0,165,23.88,Normal
10,SC60908,Nabila Salmaa Azzahra,Management,59.0,170,20.42,Normal
24,SC60916,Muhammad Iqbal,Oseanografi,55.0,167,19.72,Normal
4,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168,23.74,Normal
17,SC60904,Maulana Raji Shofil Fuadi,Aktuaria,67.0,170,23.18,Normal
3,SC60906,Lisa Nessa Safitri,Matematika,43.0,149,19.37,Normal
9,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153,17.94,Underweight
0,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167,24.02,Normal
13,SC60905,Haris Munandar,Teknik Pertanian,70.0,173,23.39,Normal
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01,Underweight
15,SC60921,Faris Reza Hutama,Statistika,47.0,168,16.65,Underweight
14,SC60903,Dede Meilawati,Sistem Informasi,55.0,159,21.76,Normal
6,SC60913,Deana Nathania Damayanti,Informatika,50.0,165,18.37,Underweight
11,SC60920,Aufa Fahmi Widyatna,Matematika,55.0,167,19.72,Normal
20,SC60902,Asmiranti,Teknologi Informasi,49.9,152,21.60,Normal
8,SC60912,Alvina Az-Zahra Adiputri,Statistika,50.0,159,19.78,Normal
18,SC60919,Ahmad Rosyiq Al Farisi,Geofisika,50.0,160,19.53,Normal
22,SC60901,Afifah Mutiah Nurdin,Statistika,47.0,155,19.56,Normal

## 7. Filter dataframe df berdasarkan:
*   Status BMI di luar Normal.
*   Tinggi Badan > 169 cm dan Berat Badan > 60 kg.
*   Nama yang mengandung huruf "y".
*   Siapa saja yang berat badannya kurang dari 60 kg?

In [ ]:
#Soal a
df_a = df[df['Status BMI'] != 'Normal']
df_a

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
1,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01,Underweight
6,SC60913,Deana Nathania Damayanti,Informatika,50.0,165,18.37,Underweight
9,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153,17.94,Underweight
12,SC60918,Silviana Siagian,Sistem Informasi,45.0,165,16.53,Underweight
15,SC60921,Faris Reza Hutama,Statistika,47.0,168,16.65,Underweight

In [ ]:
#Soal b
df_b = df[(df['Tinggi Badan (cm)'] > 169) & (df['Berat Badan (kg)'] > 60)]
df_b

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
13,SC60905,Haris Munandar,Teknik Pertanian,70.0,173,23.39,Normal
17,SC60904,Maulana Raji Shofil Fuadi,Aktuaria,67.0,170,23.18,Normal

In [ ]:
#Soal c
df_c = df[df['Nama Lengkap'].str.contains('y')]
df_c

,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
2,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64,Normal
5,SC60923,Najwa Mayang Vianisa,Statistika,65.0,165,23.88,Normal
6,SC60913,Deana Nathania Damayanti,Informatika,50.0,165,18.37,Underweight
9,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153,17.94,Underweight
11,SC60920,Aufa Fahmi Widyatna,Matematika,55.0,167,19.72,Normal
18,SC60919,Ahmad Rosyiq Al Farisi,Geofisika,50.0,160,19.53,Normal
19,SC60924,Reza Sadiya Purwadwika,Sains Data,55.0,163,20.70,Normal
21,SC60917,Paskahlin Pretty,MANAJEMEN,60.0,165,22.04,Normal

In [ ]:
#Soal d
df_d = df[['Nama Lengkap','Berat Badan (kg)']][df['Berat Badan (kg)'] < 60]
df_d

                    Nama Lengkap  Berat Badan (kg)
1   Felicitia Ifianasa Lathifah               48.0
2            Vidya Sinta Billkis              52.0
3            Lisa Nessa Safitri               43.0
6       Deana Nathania Damayanti              50.0
7             Tiara Dwi Maharani              55.0
8       Alvina Az-Zahra Adiputri              50.0
9           Kyla Letizia Denisha              42.0
10         Nabila Salmaa Azzahra              59.0
11           Aufa Fahmi Widyatna              55.0
12              Silviana Siagian              45.0
14                Dede Meilawati              55.0
15            Faris Reza Hutama               47.0
16             PANGKY MANGKURAJA              52.0
18        Ahmad Rosyiq Al Farisi              50.0
19        Reza Sadiya Purwadwika              55.0
20                     Asmiranti              49.9
22          Afifah Mutiah Nurdin              47.0
23        Roisatul Laila Hikmah               50.0
24               Muhammad Iqbal               55.0

## 8. Tambahkan nomor urut pada dataframe df sesuai jumlah siswa dan tempatkan kolom nomor baru tersebut di paling ujung kiri sebagai kolom pertama serta beri nama kolomnya "No."!

In [ ]:
#Menambahkan Kolom Nomor Urut
df.insert(0, 'No.', list(range(1, (len(df))+1)))

In [ ]:
#Memanggil dataframe df
df

,No.,Nomor Peserta,Nama Lengkap,Jurusan,Berat Badan (kg),Tinggi Badan (cm),BMI,Status BMI
0,1,SC60922,Kevin Unedo Samosir,Sistem Informasi,67.0,167,24.02,Normal
1,2,SC60914,Felicitia Ifianasa Lathifah,Matematika,48.0,168,17.01,Underweight
2,3,SC60925,Vidya Sinta Billkis,Ilmu Komputer,52.0,155,21.64,Normal
3,4,SC60906,Lisa Nessa Safitri,Matematika,43.0,149,19.37,Normal
4,5,SC60907,Muhamad Fais Halim Jauzi,Teknik Elektronika,67.0,168,23.74,Normal
5,6,SC60923,Najwa Mayang Vianisa,Statistika,65.0,165,23.88,Normal
6,7,SC60913,Deana Nathania Damayanti,Informatika,50.0,165,18.37,Underweight
7,8,SC60911,Tiara Dwi Maharani,Ekonomi,55.0,156,22.60,Normal
8,9,SC60912,Alvina Az-Zahra Adiputri,Statistika,50.0,159,19.78,Normal
9,10,SC60915,Kyla Letizia Denisha,Ilmu ekonomi,42.0,153,17.94,Underweight
10,11,SC60908,Nabila Salmaa Azzahra,Management,59.0,170,20.42,Normal
11,12,SC60920,Aufa Fahmi Widyatna,Matematika,55.0,167,19.72,Normal
12,13,SC60918,Silviana Siagian,Sistem Informasi,45.0,165,16.53,Underweight
13,14,SC60905,Haris Munandar,Teknik Pertanian,70.0,173,23.39,Normal
14,15,SC60903,Dede Meilawati,Sistem Informasi,55.0,159,21.76,Normal
15,16,SC60921,Faris Reza Hutama,Statistika,47.0,168,16.65,Underweight
16,17,SC60909,PANGKY MANGKURAJA,Statistika,52.0,166,18.87,Normal
17,18,SC60904,Maulana Raji Shofil Fuadi,Aktuaria,67.0,170,23.18,Normal
18,19,SC60919,Ahmad Rosyiq Al Farisi,Geofisika,50.0,160,19.53,Normal
19,20,SC60924,Reza Sadiya Purwadwika,Sains Data,55.0,163,20.70,Normal
20,21,SC60902,Asmiranti,Teknologi Informasi,49.9,152,21.60,Normal
21,22,SC60917,Paskahlin Pretty,MANAJEMEN,60.0,165,22.04,Normal
22,23,SC60901,Afifah Mutiah Nurdin,Statistika,47.0,155,19.56,Normal
23,24,SC60910,Roisatul Laila Hikmah,Pendidikan IPA,50.0,156,20.55,Normal
24,25,SC60916,Muhammad Iqbal,Oseanografi,55.0,167,19.72,Normal

## 9. Cari nilai-nilai berikut:
*   Cari nilai terendah dan tertingginya.
*   Berapa nilai rata-rata tinggi badan siswa?
*   Berapa rata-rata berat badan siswa?
*   Ada berapa jumlah orang yang tercatat pada dataframe?
*   5 orang dengan nilai BMI tertinggi.
*   Ada berapa orang yang tergolong status Underweight, Normal, Overweight, dan Obesity?

In [ ]:
#Maksimum dan Minimum
##Tinggi Badan
nilai_tertinggi = df['Tinggi Badan (cm)'].max()
nilai_terendah = df['Tinggi Badan (cm)'].min()
print('Nilai tertinggi dari tinggi badan siswa:', nilai_tertinggi, 'cm')
print('Nilai terendah dari tinggi badan siswa:', nilai_terendah, 'cm')
##Berat Badan
nilai_tertinggi = df['Berat Badan (kg)'].max()
nilai_terendah = df['Berat Badan (kg)'].min()
print('Nilai tertinggi dari berat badan siswa:', nilai_tertinggi, 'kg')
print('Nilai terendah dari berat badan siswa:', nilai_terendah, 'kg')

Nilai tertinggi dari tinggi badan siswa: 173 cm
Nilai terendah dari tinggi badan siswa: 149 cm
Nilai tertinggi dari berat badan siswa: 70.0 kg
Nilai terendah dari berat badan siswa: 42.0 kg

In [ ]:
#Rata-Rata Tinggi Badan
ratarata = df['Tinggi Badan (cm)'].mean()
print('Nilai rata-rata tinggi badan siswa:',round(ratarata,2),'cm')

Nilai rata-rata tinggi badan siswa: 162.44 cm

In [ ]:
#Rata-Rata Berat Badan
ratarata = df['Berat Badan (kg)'].mean()
print('Nilai rata-rata berat badan siswa:',round(ratarata,2),'kg')

Nilai rata-rata berat badan siswa: 54.24 kg

In [ ]:
#Jumlah Siswa
jmlsiswa = len(df)
print('Jumlah siswa yang tercatat pada dataframe df:', jmlsiswa)

Jumlah siswa yang tercatat pada dataframe df: 25

In [ ]:
#Top 5 BMI tertinggi
top5 = df.nlargest(5, 'BMI')
top5_nama = top5[['Nama Lengkap','BMI']]
print(top5_nama)

                 Nama Lengkap    BMI
0         Kevin Unedo Samosir  24.02
5        Najwa Mayang Vianisa  23.88
4    Muhamad Fais Halim Jauzi  23.74
13             Haris Munandar  23.39
17  Maulana Raji Shofil Fuadi  23.18

In [ ]:
#Klasifikasi Siswa Berdasarkan Status BMI
statusBMI = df['Status BMI'].value_counts()
print(statusBMI)

Normal         20
Underweight     5
Name: Status BMI, dtype: int64

# **SOAL 2**

Perusahaan Investasi Jamin-Sugih Co kami memberikan penawaran investasi terbaik dengan pembagian keuntungan tetap sebesar 25% setiap tahun.

Buatlah program Python yang dapat menerima input dari pengguna dalam bentuk:
Modal Investasi (bilangan bulat antara 0-1.000.000.000)
Jangka Waktu Investasi (bilangan bulat antara 1-25 dalam tahun)
Selain itu, program akan menampilkan error message bahwa modal atau tenure tidak sesuai ketentuan.

Program akan menampilkan informasi akumulasi investasi setiap tahun, menggunakan iterasi untuk setiap tahun.

In [ ]:
def calculate_investment(money_capital, tenure):
    # Cek apakah modal dan jangka waktu sesuai ketentuan
    if not (0 < money_capital <= 1000000000) or not (0 < tenure <= 25):
        print('Error: Modal atau jangka waktu tidak sesuai ketentuan.')
        return

    # Inisialisasi variabel akumulasi investasi
    total_investment = money_capital

    # Iterasi untuk setiap tahun
    for year in range(1, tenure + 1):
        # Hitung keuntungan dan akumulasi investasi
        profit = total_investment * 0.25
        total_investment += profit

        # Tampilkan hasil setiap tahun
        print(f'Year {year}, your total investment: {total_investment}')

# Menerima input dari pengguna
try:
    money_capital = int(input('>> Money Capital: '))
    tenure = int(input('>> Investment Tenure (years): '))
except ValueError:
    print('Error: Masukkan harus berupa bilangan bulat.')
    exit()

# Panggil fungsi untuk menghitung investasi
calculate_investment(money_capital, tenure)

>> Money Capital: 100000
>> Investment Tenure (years): 2
Year 1, your total investment: 125000.0
Year 2, your total investment: 156250.0